[!] DB 연결 실패 또는 데이터 없음: Error HTTPConnectionPool(host='10.3.31.442', port=8123): Max retries exceeded with url: /? (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000025289A93590>: Failed to resolve '10.3.31.442' ([Errno 11001] getaddrinfo failed)")) executing HTTP request attempt 1 (http://10.3.31.442:8123)
[!] DB 연결 실패 또는 데이터 없음: Error HTTPConnectionPool(host='10.3.31.442', port=8123): Max retries exceeded with url: /? (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002BFA8253790>: Failed to resolve '10.3.31.442' ([Errno 11001] getaddrinfo failed)")) executing HTTP request attempt 1 (http://10.3.31.442:8123)
[!] DB 연결 실패 또는 데이터 없음: Error HTTPConnectionPool(host='10.3.31.442', port=8123): Max retries exceeded with url: /? (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002563DE53850>: Failed to resolve '10.3.31.442' ([Errno 11001] getaddrinfo failed)")) executing HTTP request attempt 1 (http://10.3.31.442:8123)
[!] DB 연결 실패 또는 데이터 없음: Error HTTPConnectionPool(host='10.3.31.442', port=8123): Max retries exceeded with url: /? (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000011B4BCFF350>: Failed to resolve '10.3.31.442' ([Errno 11001] getaddrinfo failed)")) executing HTTP request attempt 1 (http://10.3.31.442:8123)
[!] DB 연결 실패 또는 데이터 없음: Error HTTPConnectionPool(host='211.115.221.1', port=8123): Max retries exceeded with url: /? (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F315483B50>, 'Connection to 211.115.221.1 timed out. (connect timeout=10)')) executing HTTP request attempt 1 (http://211.115.221.1:8123)
[!] DB 연결 실패 또는 데이터 없음: Error HTTPConnectionPool(host='211.115.221.1', port=8123): Max retries exceeded with url: /? (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000176019681D0>, 'Connection to 211.115.221.1 timed out. (connect timeout=10)')) executing HTTP request attempt 1 (http://211.115.221.1:8123)
[!] DB 연결 실패 또는 데이터 없음: Error HTTPConnectionPool(host='211.115.221.1', port=8123): Max retries exceeded with url: /? (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A77EA83A50>, 'Connection to 211.115.221.1 timed out. (connect timeout=10)')) executing HTTP request attempt 1 (http://211.115.221.1:8123)
